language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t rcsillag/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rcsillag/docker-react npm run test
